name: test work flow
on: workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: actions/checkout@v3
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: list job
        run: echo "Lint job1 step"
      - name: lint job2
        run: echo "Lint job2 step"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dep job1
        run: echo "Dep job1 step"
      - name: Dep Job2
        run: echo "Dep job2 step"        
          
      
